### ISSUE TITLE
Unpatching Harmony patches

### ISSUE THREAD

**Issue by MarijnS95** [SubnauticaNitrox/Nitrox#34]
Add functionality to remove Harmony patches from the game when the player leaves a session. There is a fork+PR of Harmony doing exactly this.

We should probably make a fork under SubnauticaNitrox, where our modified version of Harmony lives. It's a good idea to move the reloader into there as well (it uses a very similar codebase), and unify reloading/injecting of methods.

### TODO:
- [x] Clone Harmony under the SubnauticaNitrox organization.
- [x] Add project to Nitrox repo & sln (with submodules?).
- [x] Merge in unpatching code from other Harmony fork.
- [x] Refactor our init code to be easily injected and removed.
      - Only the multiplayer button (and for devs the `mplayer` dev command) need to be loaded in.
      - Does this mean we should unload patches on typing `disconnect`, or on return to the menu?
      - Idea: Use namespace similar to how server patches are distinguished from client patches? (and migrate client stuff to `NitroxPatcher.Patches.Client`).
- [ ] Migrate reloader to Harmony.
- [ ] Unify reloading and patching (both tasks are almost identical, though Harmony is a bit of a ... to modify/work with).

### Further reloader ideas:
- [ ] 'field' reloader (add an attribute to a field, and it'll get initialized to it's default value on reload).
- [ ] Fix type usage: When a type is in a reloaded assembly, that one is referenced instead (by reloaded code). When doing operations on these types, the wrong types are referenced and everything breaks.
  - Operations that use types to search (`GetComponent<SomeTypeInReloadedAssembly>()` suddenly returns `null`).
  - Static field references.
  - [x] Method finding with parameter-types (such as in the reloader itself, this was fixed in https://github.com/MarijnS95/Nitrox/commit/9c5bcb475cc0b65d1bdb06bef3eec9f72be497c9).

**Comment by Sunrunner37** [comment]
Cloned harmony under the org.  I'll try to figure out the changes that I made to make harmony unit test compatible and apply them to the new repo.

**Comment by Jannify** [comment]
Is this still needed since we have a launcher ?

**Comment by MarijnS95** [comment]
@Jannify IMO the launcher shouldn't be a replacement for this, yet it is. Though afaik all the necessary features have been implemented. The reloaders is just extra fluff, which has in fact been removed entirely due to the to-be-resolved issues listed above.
