### ISSUE TITLE
Improvement: Use lidgren as backend for networking

### ISSUE THREAD

**Issue by Measurity** [SubnauticaNitrox/Nitrox#87]
https://github.com/lidgren/lidgren-network-gen3

## About Lidgren
[Lidgren uses a single UDP channel and allows specific messages to be delivered reliable, in sequence, both or neither for lowest latency.](https://github.com/lidgren/lidgren-network-gen3/wiki/Features)

[Easy to add encryption](https://github.com/lidgren/lidgren-network-gen3/wiki/Message-Encryption)
[Local network server discovery](https://github.com/lidgren/lidgren-network-gen3/wiki/Discovery)

## Why change?
Current network stack uses TCP which has poor latency for updating entity positions or in other high-frequency communication requirements. Lidgren offers more flexibility than what is currently in code so it will give an edge both in time and features.

Because there's still a lot of work to do I think it's best to change this asap.

## I need help with understanding multiplayer features as-is
I would like to make this improvement myself but I'm not sure what works now and what doesn't. Connecting seems to be very manual (through console commands) and I don't have another player to test with. If someone could help me with explaining their current workflow on testing multiplayer it'll help a lot.

## Research plan

- [ ] Develop network debugging UI with statistics of the current network stack.
- [ ] Document current networking statistics, explore edge-case situations.
- [ ] Implement another network stack with Lidgren in a new branch.
- [ ] Document new network stack and explore edge-case situations.
- [ ] Research current feature list of both network stacks.
- [ ] Compare side-by-side and decide.

## Implementation plan

1. Create branch 'feature-netcode'
2. Create sub-project: "Nitrox.Networking".
3. Add Lidgren as dependency, move packet and serialization classes to it.
4. Implement NitroxClient/NitroxServer classes using Lidgren backend.
5. Extend packet class so that method-of-deliver can be specified.
6. Allow packets to be 'registered' so that both NitroxClient and NitroxServer can work.
7. Test it ;)

**Comment by MarijnS95** [comment]
The current multiplayer connection workflow may be considered a little temporary (though you have to check with the maintainer @Sunrunner37 to be sure), as plans are made to modify the current system. Both in terms of data transmission as well as serialisation. I personally agree there's a bunch of code related to networking that's much better dealt with by a separate library. Saves us the hassle of maintaining and debugging (for example, take a look at `MessageBuffer`, which collects data from the TCP and assembles objects from it. And similarly, the `PriorityQueue` which can be much simplified or completely handed off to some builtin classes).

For instance, I've been looking into the various Steam socket and P2P transport systems, to provide a smooth experience utilizing Steam's relay servers when necessary. Besides, this requires the game to be owned legitimately through Steam.
In the end, I've refactored the connection system to allow both the TCP socket and Steam sockets to work interchangeably, and with a little more modification they can operate simultaneously (the only thing holding it back now is actually figuring out how to run the external server without someone logging in there and preventing them from playing the game). IMHO it'd be great to have a simple network interface to program against, such that we can easily add or modify transport mechanisms, and as a means to separate the multiplayer code from the network implementation more strictly.

**Comment by Measuring** [comment]
@MarijnS95 Using Steam network would be ideal. I don't know if there are legal and/or economical issues.

**Comment by Measuring** [comment]
@MarijnS95 Using Steam would be ideal. Are you sure there are no legal/economical issues for the mod or the Subnautica developers?

**Comment by MarijnS95** [comment]
There is none, as far as I know. Though I haven't put any work into it for a long time. Would be important to figure out before continuing. That is, if I can get it to work and figure out/work around the limitations.

**Comment by Sunrunner37** [comment]
@Measuring - Thanks for the well thought out post.  To give you some background, the existing TCP code was forked from another project that I worked on.  We have gotten a lot of mileage out of it but it was never considered to be a permanent solution.  I think as a general guidance we want to keep the current structure of the packet processors (as they are already implemented and intuitive) but definitely open to changing out things 'under-the-hood' like transmission and serialization.

As for steam integration - I want to be careful before we throw our implementation on them.  We don't want to introduce new limitations like users not being able to host servers while playing or requiring the server to have an instance of steam running.  Let alone any of the steam tos or legal implications.  I think in order to make this switch we would need strong justification and a full understanding of what we are gaining.

Going back to the original topic, if we decide that the TCP layer is a bottleneck and would like to make significant changes, then it would be best to do a lot of research first.  We should first identify to what extent this is causing us pain and by how much we can improve it.  Some general questions we should answer or benchmark:

1) What are the existing characteristics of the system (latency, throughput, max connections)?
2) To what extent are these noticeable by end users?
3) How will the new system affect these characteristics?
4) At what point does our current system break down?  How about the new system?
5) Are there any new risks that switching the infrastructure introduces?
6) What is the cost of making a switch?  Opportunity cost?
7) What is the cost of doing this optimization at a future point in time?

I believe that this will help us make a data-driven decision.  It would be cool to prototype this, do some benchmarking, and see where we come out.

**Comment by Measuring** [comment]
@Sunrunner37 I'll do the research. Just a headsup that it might take a while for me to properly do so because I'm new to this project.

**Comment by MadMaxOfYore** [comment]
Just wanted to give y'all a heads up that I'll be dropping a PR in the next day or two that deals with this space. My PR deals specifically with enforcing unique player names during the join process, but involved a lot of work *around* the TcpClient and packet transmission in general.

While I did not mess with the TcpClient much, (other than to clean up the communication between it and the Multiplayer behavior) I did invert the dependency by extracting the current public API into an interface and diverted all references to TcpClient to IClient.

I wanted to mention that simply so you can factor that into your research. We should be able to make a wholesale swap of the underlying transmission protocol without needing to change any of the consumers.

It we can get an IoC framework in the mix, then it becomes even easier.

**Comment by Coding-Hen** [comment]
Can't this now be closed as it was removed as per b58131170d74d409abafaf5360cfb55964a2ea54
